// Generated by CoffeeScript 1.12.2
let getNanoSeconds: any = null
let hrtime: any = null;
let loadTime: any = null;
let moduleLoadTime: any = null;
let nodeLoadTime: any = null;
let upTime: any;


const now = () => {
  if ((typeof performance !== "undefined" && performance !== null) && performance.now) {
    return performance.now();
  } else if ((typeof process !== "undefined" && process !== null) && process.hrtime) {
    hrtime = process.hrtime;
    getNanoSeconds = function () {
      var hr;
      hr = hrtime();
      return hr[0] * 1e9 + hr[1];
    };
    moduleLoadTime = getNanoSeconds();
    upTime = process.uptime() * 1e9;
    nodeLoadTime = moduleLoadTime - upTime;
    return (getNanoSeconds() - nodeLoadTime) / 1e6;
  } else if (Date.now) {
    loadTime = Date.now();
    return Date.now() - loadTime;
  } else {
    loadTime = new Date().getTime();
    return new Date().getTime() - loadTime;
  }
}



export default now

