"use strict";
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const copy = require("./copy/copy.js");
const dom = require("./dom.js");
exports.Copy = copy.default;
exports.getScroll = dom.getScroll;
exports.getScrollContainer = dom.getScrollContainer;
exports.off = dom.off;
exports.on = dom.on;
exports.scrollTo = dom.scrollTo;
